blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogPostListView.as_view(), name='blogs'),
    path('blog/<uuid:pk>', views.BlogPostDetailView.as_view(), name='blogpost-detail'),
    path('blog/<uuid:pk>/create-comment/', views.BlogCommentCreate.as_view(), name='blogcomment-create'),
    path('bloggers/', views.BlogAuthorListView.as_view(), name='bloggers'),
    path('blogger/<int:pk>', views.BlogAuthorDetailView.as_view(), name='blogauthor-detail'),
]

miniblog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Use include() to add paths from the catalog application
    path('blog/', include('blog.urls')),
    # Add URL maps to redirect the base URL to the application
    path('', RedirectView.as_view(url='blog/', permanent=True)),
    # Add Django site authentication urls (for login, logout, password management)
    path('accounts/', include('django.contrib.auth.urls')),
]
# Use static() to add url mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
import uuid # Used for unique blog post instances

from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

class BlogAuthor(models.Model):
    """Model representing a blog post author."""

    name = models.CharField(max_length=200, help_text='Enter name of author of blog.')
    bio = models.TextField(max_length=1000, help_text='Enter biography about author of blog.')

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        """Returns the url to access a particular instance of BlogAuthor."""
        return reverse('blogauthor-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.name

class BlogPost(models.Model):
    """Model representing a blog post."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular blog post.')
    title = models.CharField(max_length=200, help_text='Enter title of blog post.')
    post_date = models.DateField(auto_now_add=True, verbose_name='Post Date')
    author = models.ForeignKey(BlogAuthor, on_delete=models.CASCADE)
    description = models.TextField(max_length=10000, help_text='Enter main content text of blog post.')

    class Meta:
        ordering = ['-post_date']

    def get_absolute_url(self):
        """Returns the url to access a particular instance of BlogPost."""
        return reverse('blogpost-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.title} - {self.author}'

class BlogComment(models.Model):
    """Model representing a comment"""

    post_date_time = models.DateTimeField(auto_now_add=True, verbose_name='Post Date')
    author = models.CharField(max_length=200, help_text='Enter username of the blog comment.')
    description = models.TextField(max_length=1000, help_text='Enter content of blog comment.')
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, verbose_name='Blog Post')

    class Meta:
        ordering = ['post_date_time']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.author} - {self.description}'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import fields
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import generic
from .models import BlogPost, BlogAuthor, BlogComment

# Create your views here.
def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_posts = BlogPost.objects.count()
    num_authors = BlogAuthor.objects.count()
    num_comments = BlogComment.objects.count()

    # Number of visits to this view, as counted in the session variable
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_posts': num_posts,
        'num_authors': num_authors,
        'num_comments': num_comments,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context)

class BlogPostListView(generic.ListView):
    model = BlogPost
    paginate_by = 5

class BlogPostDetailView(generic.DetailView):
    model = BlogPost

class BlogAuthorListView(generic.ListView):
    model = BlogAuthor
    paginate_by = 5

class BlogAuthorDetailView(generic.DetailView):
    model = BlogAuthor

class BlogCommentCreate(LoginRequiredMixin, generic.edit.CreateView):
    model = BlogComment
    fields = ['description']

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        # Get the blog post object from the "pk" parameter and add it to the context
        context['blogpost'] = get_object_or_404(BlogPost, pk = self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """
        Add author and associated blog to form data before saving it as valid (so it is saved to model)
        """
        # Add logged-in user as author of comment
        form.instance.author = self.request.user

        # Associate comment with blog post based on passed id
        form.instance.blog_post = get_object_or_404(BlogPost, pk = self.kwargs['pk'])

        # Call super-class form validation behavior
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self):
        return get_object_or_404(BlogPost, pk = self.kwargs['pk']).get_absolute_url()

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}<title>Django Mini Blog</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <!-- Add additional CSS in static file -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'blogs' %}">All Blog Posts</a></li>
                        <li><a href="{% url 'bloggers' %}">All Blog Authors</a></li>
                        <br/>
                        {% if user.is_authenticated %}
                            <li>User: {{ user.get_username }}</li>
                            <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                        {% endif %}
                    </ul>
                {% endblock %}
                </div>
                <div class="col-sm-10">
                    {% block content %}{% endblock %}
                    {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                    {% endif %}
                                    <span class="page-current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/blog_post_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blog Post List</h1>
    {% if blog_post_list %}
        <ul>
            {% for blog_post in blog_post_list %}
                <li>
                    <a href="{{ blog_post.get_absolute_url }}">{{ blog_post.title }}</a> - {{ blog_post.post_date }} - <a href="">{{ blog_post.author }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no blog posts.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/blogauthor_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blogger: {{ blogauthor.name }}</h1>

    <h2>Bio</h2>

    <p>{{ blogauthor.bio }}</p>

    <h2>Blogs List</h2>
        <ul>
            {% for blogpost in blogauthor.blogpost_set.all %}
                <li><a href="{{ blogpost.get_absolute_url }}">{{ blogpost.title }}</a> ({{ blogpost.post_date }})</li>
            {% endfor %}
        </ul>
{% endblock %}

blog/templates/blog/blogauthor_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Bloggers</h1>
    {% if blogauthor_list %}
        <ul>
            {% for blogauthor in blogauthor_list %}
                <li>
                    <a href="{{ blogauthor.get_absolute_url }}">{{ blogauthor.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no blog authors.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/blogcomment_form.html
{% extends "base_generic.html" %}

{% block content %}
    <p>Post your comment for: <a href="{{ blogpost.get_absolute_url }}">{{ blogpost.title }}</a></p>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>{{ blogpost.title }}</h1>

    <p><strong>Post Date:</strong> {{ blogpost.post_date }}</p>
    <p><strong>Author:</strong> <a href="{{ blogpost.author.get_absolute_url }}">{{ blogpost.author }}</a></p>
    <p><strong>Description:</strong></p>
    <p>{{ blogpost.description }}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Comments</h4>

        {% for comment in blogpost.blogcomment_set.all %}
            <hr>
            <p>{{ comment.author }} ({{ comment.post_date_time }}) - {{ comment.description }}</p>
        {% endfor %}
        <a href="{% url 'blogcomment-create' blogpost.id %}">Add a new comment</a>
    </div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Blogs</h1>
    {% if blogpost_list %}
        <ul>
            {% for blogpost in blogpost_list %}
                <li>
                    <a href="{{ blogpost.get_absolute_url }}">{{ blogpost.title }}</a> ({{ blogpost.post_date }}) - <a href="{{ blogpost.author.get_absolute_url }}">{{ blogpost.author }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no blog posts.</p>
    {% endif %}
{% endblock %}

blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Django Mini Blog Home</h1>
<p>Welcome to Django Mini Blog, a website developed using Django!</p>
<h2>Dynamic Content</h2>
<p>The mini blog has the following:</p>
<ul>
    <li><strong>Posts:</strong> {{ num_posts }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Comments:</strong> {{ num_comments }}</li>
</ul>

<p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
{% endblock %}